# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_BargerPropagator', [dirname(__file__)])
        except ImportError:
            import _BargerPropagator
            return _BargerPropagator
        if fp is not None:
            try:
                _mod = imp.load_module('_BargerPropagator', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _BargerPropagator = swig_import_helper()
    del swig_import_helper
else:
    import _BargerPropagator
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class BargerPropagator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BargerPropagator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BargerPropagator, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _BargerPropagator.new_BargerPropagator(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _BargerPropagator.delete_BargerPropagator
    __del__ = lambda self : None;
    def propagate(self, *args): return _BargerPropagator.BargerPropagator_propagate(self, *args)
    def propagateLinear(self, *args): return _BargerPropagator.BargerPropagator_propagateLinear(self, *args)
    def GetVacuumProb(self, *args): return _BargerPropagator.BargerPropagator_GetVacuumProb(self, *args)
    def DefinePath(self, *args): return _BargerPropagator.BargerPropagator_DefinePath(self, *args)
    def SetMNS(self, *args): return _BargerPropagator.BargerPropagator_SetMNS(self, *args)
    def SetDensityConversion(self, *args): return _BargerPropagator.BargerPropagator_SetDensityConversion(self, *args)
    def GetProb(self, *args): return _BargerPropagator.BargerPropagator_GetProb(self, *args)
    def GetPathLength(self): return _BargerPropagator.BargerPropagator_GetPathLength(self)
    def SetPathLength(self, *args): return _BargerPropagator.BargerPropagator_SetPathLength(self, *args)
    def SetEnergy(self, *args): return _BargerPropagator.BargerPropagator_SetEnergy(self, *args)
    def SetMatterPathLength(self): return _BargerPropagator.BargerPropagator_SetMatterPathLength(self)
    def SetAirPathLength(self, *args): return _BargerPropagator.BargerPropagator_SetAirPathLength(self, *args)
    def UseMassEigenstates(self, *args): return _BargerPropagator.BargerPropagator_UseMassEigenstates(self, *args)
    def SetWarningSuppression(self, x=True): return _BargerPropagator.BargerPropagator_SetWarningSuppression(self, x)
    def SetOneMassScaleMode(self, x=True): return _BargerPropagator.BargerPropagator_SetOneMassScaleMode(self, x)
BargerPropagator_swigregister = _BargerPropagator.BargerPropagator_swigregister
BargerPropagator_swigregister(BargerPropagator)

# This file is compatible with both classic and new-style classes.


